version: '3.3'

services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: localwpuser
      WORDPRESS_DB_PASSWORD: localwppass
      WORDPRESS_DB_NAME: localwpdb
    volumes:
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/wp-config.php:/var/www/html/wp-config.php

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: localwpdb
      MYSQL_USER: localwpuser
      MYSQL_PASSWORD: localwppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080

networks:
  back:


volumes:
  db:
